#pragma once
#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <HTTPClient.h>
#include <vector>
#include <unordered_map>

#include "EEPROM.h"
#include "ArduinoJson-v7.4.3.h"
#include "Wienerlinen.cpp"

// ── Shared helper: fetch a URL, return body or empty string ──────

String fetchPage(const char* url) {
    HTTPClient http;
    http.useHTTP10(true);
    http.setTimeout(8000);
    http.begin(url);
    http.setUserAgent("ESP32-Proxy/1.0");
    String body;
    if(http.GET() == HTTP_CODE_OK) body = http.getString();
    http.end();
    return body;
}

// ── Helper: safe extract of LineStop.name (max 3 chars, null‑terminated) ──

String lineStopName(const WienerLinienStation::LineStop& ls) {
    String s;
    s.reserve(3);
    for(char c : ls.name) { if(c == '\0') break; s += c; }
    return s;
}

// ── Helper: fast integer parse from a char range ─────────────────

int fastParseInt(const char* s, size_t len) {
    int v = 0;
    for(size_t i = 0; i < len && s[i] >= '0' && s[i] <= '9'; i++)
        v = v * 10 + (s[i] - '0');
    return v;
}

// ── WiFi setup portal page (served during AP mode) ──────────────

String getWifiSetupHTML() {
  return R"rawliteral(
<!DOCTYPE html>
<html>
<head>
  <title>WiFi Setup - Wiener Linien Display</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body{font-family:sans-serif;max-width:400px;margin:0 auto;padding:20px;background:#f5f5f5}
    h1{font-size:1.3em;color:#333}
    p{color:#666}
    label{display:block;margin:12px 0 4px;font-weight:bold;color:#333}
    input{width:100%;padding:10px;border:1px solid #ccc;border-radius:4px;font-size:1em;box-sizing:border-box}
    button{margin-top:16px;width:100%;padding:12px;font-size:1em;background:#4CAF50;color:white;border:none;border-radius:4px;cursor:pointer}
    button:hover{background:#45a049}
    #status{margin-top:12px;font-size:0.9em;min-height:1.2em}
  </style>
</head>
<body>
  <h1>WiFi Setup</h1>
  <p>Configure your home WiFi network for the Wiener Linien Display.</p>
  <form id="wifiForm">
    <label for="ssid">SSID (Network Name):</label>
    <input type="text" id="ssid" name="ssid" required placeholder="Your WiFi name" autofocus>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" placeholder="WiFi password">
    <button type="submit">Save &amp; Connect</button>
  </form>
  <div id="status"></div>
  <script>
    document.getElementById('wifiForm').addEventListener('submit', async function(e){
      e.preventDefault();
      var s=document.getElementById('status');
      s.textContent='Saving...';s.style.color='#333';
      var p=new URLSearchParams();
      p.append('ssid',document.getElementById('ssid').value);
      p.append('password',document.getElementById('password').value);
      try{
        var r=await fetch('/',{method:'POST',body:p});
        if(r.ok){s.textContent='Saved! Rebooting...';s.style.color='green';}
        else{s.textContent='Error saving credentials.';s.style.color='red';}
      }catch(e){s.textContent='Connection error.';s.style.color='red';}
    });
  </script>
</body>
</html>
)rawliteral";
}

// --- EMBEDDED_HTML_BEGIN ---
// This section is auto-generated by tools/embed_html.py from index.html.
// Do not edit by hand -- edit index.html instead.
String getIndexHTML() {
  return R"rawliteral(
<!DOCTYPE html>
<html>
<head>
  <title>Wiener Linien - Stops</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body{font-family:sans-serif;max-width:600px;margin:0 auto;padding:16px}
    h1{font-size:1.4em}
    h3{font-size:1.1em;margin:16px 0 8px}
    .stop-item{display:flex;align-items:center;gap:8px;padding:6px 8px;border-bottom:1px solid #eee}
    .stop-item button{margin-left:auto;background:none;border:1px solid #ccc;border-radius:4px;cursor:pointer;padding:2px 8px;font-size:1em}
    .stop-item button:hover{background:#fdd;border-color:#c00}
    .station{display:block;cursor:pointer;padding:6px 10px;margin:3px 0;border:1px solid #ccc;border-radius:4px;background:#fafafa}
    .station:hover{background:#ddf}
    .station small{color:#999}
    .row{display:flex;gap:8px;margin:8px 0;align-items:center}
    .row input,.row select{flex:1;padding:6px;border:1px solid #ccc;border-radius:4px;font-size:0.95em}
    .row button{padding:6px 16px;border:1px solid #888;border-radius:4px;background:#eee;cursor:pointer}
    .row button:hover{background:#ddd}
    .row button:disabled{opacity:0.5;cursor:default}
    .hint{font-size:0.8em;color:#999}
    .empty{color:#999;font-style:italic}
    #status{margin-top:8px;font-size:0.9em;min-height:1.2em}
    .error{color:#c00}
    .success{color:#080}
    hr{margin:16px 0;border:none;border-top:1px solid #ddd}
    #deleteAllBtn{padding:6px 12px;background:#fff;border:1px solid #ccc;border-radius:4px;cursor:pointer;font-size:0.9em}
    #deleteAllBtn:hover{background:#fdd;border-color:#c00}
    .alert-toggle{background:none;border:1px solid #aaa;border-radius:4px;cursor:pointer;padding:2px 8px;font-size:0.85em}
    .alert-toggle:hover{background:#eef;border-color:#66f}
    .alert-config{display:none;margin:6px 0 6px 16px;padding:8px;border:1px solid #ddd;border-radius:4px;background:#f9f9f9}
    .alert-config h4{font-size:0.95em;margin:0 0 8px}
    .alert-rule{display:flex;align-items:center;gap:6px;padding:3px 0;font-size:0.85em;border-bottom:1px dotted #eee}
    .alert-rule button{background:none;border:1px solid #ccc;border-radius:3px;cursor:pointer;padding:0 6px;font-size:0.85em}
    .alert-rule button:hover{background:#fdd;border-color:#c00}
    .weekday-checkboxes{display:flex;gap:4px;flex-wrap:wrap;font-size:0.82em}
    .weekday-checkboxes label{display:flex;align-items:center;gap:2px;cursor:pointer;user-select:none}
    .alert-add{margin-top:8px;padding-top:8px;border-top:1px solid #eee}
    .alert-add .row{margin:4px 0}
    .alert-add select,.alert-add input[type="time"]{padding:3px 6px;border:1px solid #ccc;border-radius:3px;font-size:0.85em}
    .alert-save-btn{padding:4px 12px;margin-top:6px;border:1px solid #4CAF50;border-radius:4px;background:#4CAF50;color:#fff;cursor:pointer;font-size:0.85em}
    .alert-save-btn:hover{background:#45a049}
    #resetWifiBtn{padding:4px 10px;margin-left:8px;background:#fff;border:1px solid #ccc;border-radius:4px;cursor:pointer;font-size:0.8em;color:#888}
    #resetWifiBtn:hover{background:#fdd;border-color:#c00;color:#c00}
  </style>
</head>
<body>
  <h1>Wiener Linien Stops</h1>

  <h3>Current Stops</h3>
  <div id="currentStops"><p class="empty">Loading...</p></div>
  <div style="margin-top: 8px; text-align: right;">
    <button id="resetWifiBtn">Reset WiFi</button>
    <button id="deleteAllBtn">Delete All</button>
  </div>

  <hr>

  <h3>Add Stop by Line</h3>
  <div class="row">
    <select id="lineSelect">
      <option value="">Loading lines...</option>
    </select>
    <button id="searchBtn" disabled>Search</button>
  </div>
  <div class="row">
    <input type="text" id="lineInput" placeholder="...or type line code manually (e.g. 302)" style="flex:1">
    <span class="hint">manual</span>
  </div>
  <div id="stationResults"></div>

  <div id="status"></div>

  <script>
    // ── Load lines from main page ───────────────────────────────

    async function loadLines() {
      const sel = document.getElementById('lineSelect');
      try {
        const res = await fetch('/api/rbl-lines');
        if(!res.ok) throw new Error('HTTP ' + res.status);
        const lines = await res.json();
        if(!lines || lines.length === 0) {
          sel.innerHTML = '<option value="">No lines found</option>';
          return;
        }
        let html = '<option value="">-- Select a line --</option>';
        for(const l of lines) {
          html += '<option value="' + l.id + '">' + esc(l.name) + ' (' + l.id + ')</option>';
        }
        sel.innerHTML = html;
      } catch(e) {
        sel.innerHTML = '<option value="">Failed to load lines</option>';
      }
    }

    function onLineSelected() {
      const sel = document.getElementById('lineSelect');
      if(!sel.value) return;
      const opt = sel.options[sel.selectedIndex];
      const lineName = opt ? opt.text.replace(/\s*\([^)]*\)\s*$/, '').trim() : '';
      document.getElementById('lineInput').value = sel.value;
      document.getElementById('lineInput').setAttribute('data-linename', lineName);
      document.getElementById('searchBtn').disabled = false;
      searchLine();
    }

    // ── Load & render stops ─────────────────────────────────────

    async function loadStops() {
      const el = document.getElementById('currentStops');
      try {
        const res = await fetch('/api/stopids');
        const data = await res.json();
        const stops = data.stops || [];
        if(stops.length === 0) {
          el.innerHTML = '<p class="empty">No stops configured.</p>';
          return;
        }
        let html = '';
        for(const s of stops) {
          const showLine = s.lineName || s.line || '';
          const label = s.name
            ? (showLine ? showLine + ' \u00b7 ' + s.name : s.name)
            : ('Stop ' + s.id);
          html += '<div class="stop-item">' +
            '<span>' + esc(label) + '</span>' +
            '<button class="alert-toggle" onclick="toggleAlerts(' + s.id + ')" title="Alert settings">\uD83D\uDD14</button>' +
            '<button onclick="deleteStop(' + s.id + ')" title="Remove">\u2715</button>' +
            '</div>' +
            '<div class="alert-config" id="alert-config-' + s.id + '">' +
            '<h4>Alert Rules</h4>' +
            '<div id="alert-rules-' + s.id + '"><p class="empty">Loading...</p></div>' +
            '<div class="alert-add">' +
            '<div class="row"><span style="font-size:0.85em;font-weight:bold">Weekdays:</span></div>' +
            '<div class="weekday-checkboxes" id="weekdays-' + s.id + '">' +
            '<label><input type="checkbox" value="0">Mon</label>' +
            '<label><input type="checkbox" value="1">Tue</label>' +
            '<label><input type="checkbox" value="2">Wed</label>' +
            '<label><input type="checkbox" value="3">Thu</label>' +
            '<label><input type="checkbox" value="4">Fri</label>' +
            '<label><input type="checkbox" value="5">Sat</label>' +
            '<label><input type="checkbox" value="6">Sun</label>' +
            '</div>' +
            '<div class="row">' +
            '<span style="font-size:0.85em">From:</span>' +
            '<input type="number" id="shh-' + s.id + '" value="7" min="0" max="23" style="width:38px;padding:3px 4px;border:1px solid #ccc;border-radius:3px;font-size:0.85em">' +
            ':<input type="number" id="shm-' + s.id + '" value="0" min="0" max="59" style="width:38px;padding:3px 4px;border:1px solid #ccc;border-radius:3px;font-size:0.85em">' +
            '<span style="font-size:0.85em;margin-left:8px">To:</span>' +
            '<input type="number" id="ehh-' + s.id + '" value="9" min="0" max="23" style="width:38px;padding:3px 4px;border:1px solid #ccc;border-radius:3px;font-size:0.85em">' +
            ':<input type="number" id="ehm-' + s.id + '" value="0" min="0" max="59" style="width:38px;padding:3px 4px;border:1px solid #ccc;border-radius:3px;font-size:0.85em">' +
            '</div>' +
            '<div class="row">' +
            '<span style="font-size:0.85em">Beep:</span>' +
            '<input type="number" id="mb-' + s.id + '" value="5" min="1" max="60" style="width:55px;padding:3px 6px;border:1px solid #ccc;border-radius:3px;font-size:0.85em"> min before' +
            '</div>' +
            '<button class="alert-save-btn" onclick="addRule(' + s.id + ')">+ Add Rule</button>' +
            '</div>' +
            '<button class="alert-save-btn" onclick="saveAlerts(' + s.id + ')" style="margin-top:8px">Save Alerts</button>' +
            '</div>';
        }
        el.innerHTML = html;
      } catch(e) {
        el.innerHTML = '<p class="error">Failed to load stops</p>';
      }
    }

    // ── Delete stop (single API call) ───────────────────────────

    async function deleteStop(id) {
      const params = new URLSearchParams();
      params.append('id', id);
      try {
        const res = await fetch('/api/delete-stop', {method:'POST', body:params});
        if(res.ok) {
          setStatus('Removed', false);
          await loadStops();
        } else {
          const data = await res.json();
          setStatus('Error: ' + (data.error || 'Failed'), true);
        }
      } catch(e) {
        setStatus('Connection error', true);
      }
    }

    // ── Delete all stops ────────────────────────────────────────

    async function deleteAllStops() {
      if (!confirm('Are you sure you want to delete all stops?')) return;
      setStatus('Deleting all stops...');
      try {
        const res = await fetch('/api/delete-all', { method: 'POST' });
        if (res.ok) {
          window.location.reload();
        } else {
          const data = await res.json().catch(() => ({}));
          setStatus('Error: ' + (data.error || 'Failed to delete all'), true);
        }
      } catch(e) {
        setStatus('Connection error', true);
      }
    }

    // ── Search line -> fetch stations from proxy ────────────────

    async function searchLine() {
      const line = document.getElementById('lineInput').value.trim();
      if(!line) return;
      setStatus('Searching line ' + line + '...');
      document.getElementById('stationResults').innerHTML = '';
      try {
        const res = await fetch('/api/rbl-stations?line=' + encodeURIComponent(line));
        if(!res.ok) {
          let msg = 'Search failed (HTTP ' + res.status + ')';
          try { const e = await res.json(); msg = e.error || msg; } catch(_) {}
          setStatus(msg, true);
          return;
        }
        const stations = await res.json();
        renderStations(stations, line);
        if(stations.length > 0) setStatus('Found ' + stations.length + ' station(s)');
        else setStatus('No stations found for line ' + line, true);
      } catch(e) {
        setStatus('Network error', true);
      }
    }

    function renderStations(stations, lineCode) {
      const el = document.getElementById('stationResults');
      if(!stations || stations.length === 0) {
        el.innerHTML = '<p class="empty">No stations returned.</p>';
        return;
      }
      let html = '<h4>Select a station to add:</h4>';
      for(const s of stations) {
        const dir = s.direction ? ' \u2192 ' + esc(s.direction) : '';
        html += '<div class="station" data-id="' + s.id +
          '" data-name="' + esc(s.name) +
          '" data-line="' + esc(lineCode) +
          '" data-dir="' + esc(s.direction || '') + '">' +
          esc(s.name) + dir + ' <small>[' + s.id + ']</small></div>';
      }
      el.innerHTML = html;
    }

    // ── Add stop: resolve RBL/StopId + save in ONE call ─────────

    async function addStop(e) {
      const div = e.target.closest('.station');
      if(!div) return;
      const stationId = div.dataset.id;
      const name      = div.dataset.name;
      const line      = div.dataset.line;
      const dir       = div.dataset.dir || '';
      const lineName  = document.getElementById('lineInput').getAttribute('data-linename') || line;

      setStatus('Adding stop...');
      const params = new URLSearchParams();
      params.append('line',     line);
      params.append('station',  stationId);
      params.append('name',     name);
      params.append('dir',      dir);
      params.append('linename', lineName);

      try {
        const res = await fetch('/api/add-stop', {method:'POST', body:params});
        const data = await res.json();
        if(res.ok) {
          document.getElementById('stationResults').innerHTML = '';
          setStatus('Added (stop ' + data.stopid + ')', false);
          await loadStops();
        } else {
          setStatus('Error: ' + (data.error || 'Failed'), true);
        }
      } catch(e) {
        setStatus('Network error', true);
      }
    }

    // ── Status display ──────────────────────────────────────────

    function setStatus(msg, isError) {
      const el = document.getElementById('status');
      el.textContent = msg;
      el.className = isError ? 'error' : 'success';
      if(!isError) {
        clearTimeout(el._timer);
        el._timer = setTimeout(function(){ el.textContent = ''; }, 3000);
      }
    }

    function esc(str) {
      return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    // ── Alert configuration ──────────────────────────────────────

    let alertConfigs = {};

    async function loadAlertConfig(stopid) {
      try {
        const res = await fetch('/api/alerts?stopid=' + stopid);
        const data = await res.json();
        alertConfigs[stopid] = data;
        renderAlertRules(stopid);
      } catch(e) {
        document.getElementById('alert-rules-' + stopid).innerHTML = '<p class="error">Failed to load</p>';
      }
    }

    function renderAlertRules(stopid) {
      const container = document.getElementById('alert-rules-' + stopid);
      const rules = (alertConfigs[stopid] && alertConfigs[stopid].rules) ? alertConfigs[stopid].rules : [];
      if (rules.length === 0) {
        container.innerHTML = '<p class="empty">No alert rules configured.</p>';
        return;
      }
      let html = '';
      for (let i = 0; i < rules.length; i++) {
        const r = rules[i];
        const wdNames = getWeekdayNames(r.wd);
        const start = pad2(r.sh) + ':' + pad2(r.sm);
        const end = pad2(r.eh) + ':' + pad2(r.em);
        html += '<div class="alert-rule">' +
          '<span>' + esc(wdNames) + ' ' + start + '-' + end + ' \u2192 beep ' + r.mb + 'min before</span>' +
          '<button onclick="deleteRule(' + stopid + ',' + i + ')" title="Remove rule">\u2715</button>' +
          '</div>';
      }
      container.innerHTML = html;
    }

    function addRule(stopid) {
      let wd = 0;
      const cbs = document.querySelectorAll('#weekdays-' + stopid + ' input[type=checkbox]');
      cbs.forEach(function(cb) { if (cb.checked) wd |= (1 << parseInt(cb.value)); });
      if (wd === 0) { setStatus('Please select at least one weekday', true); return; }

      const shhEl = document.getElementById('shh-' + stopid);
      const shmEl = document.getElementById('shm-' + stopid);
      const ehhEl = document.getElementById('ehh-' + stopid);
      const ehmEl = document.getElementById('ehm-' + stopid);
      const sh = shhEl ? parseInt(shhEl.value) || 0 : 7;
      const sm = shmEl ? parseInt(shmEl.value) || 0 : 0;
      const eh = ehhEl ? parseInt(ehhEl.value) || 0 : 9;
      const em = ehmEl ? parseInt(ehmEl.value) || 0 : 0;
      const mbEl = document.getElementById('mb-' + stopid);
      const mb = mbEl ? parseInt(mbEl.value) : 5;

      if (!alertConfigs[stopid]) alertConfigs[stopid] = { stopid: stopid, rules: [] };
      if (!alertConfigs[stopid].rules) alertConfigs[stopid].rules = [];
      alertConfigs[stopid].rules.push({ wd: wd, sh: sh, sm: sm, eh: eh, em: em, mb: mb });
      renderAlertRules(stopid);

      // Clear checkboxes for next rule
      cbs.forEach(function(cb) { cb.checked = false; });
    }

    function deleteRule(stopid, index) {
      if (!alertConfigs[stopid] || !alertConfigs[stopid].rules) return;
      alertConfigs[stopid].rules.splice(index, 1);
      renderAlertRules(stopid);
    }

    async function saveAlerts(stopid) {
      const config = alertConfigs[stopid] || { stopid: stopid, rules: [] };
      try {
        const res = await fetch('/api/alerts', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(config)
        });
        if (res.ok) {
          setStatus('Alerts saved for stop ' + stopid, false);
        } else {
          const data = await res.json().catch(function(){ return {}; });
          setStatus('Error: ' + (data.error || 'Failed to save'), true);
        }
      } catch(e) {
        setStatus('Connection error', true);
      }
    }

    function toggleAlerts(stopid) {
      const panel = document.getElementById('alert-config-' + stopid);
      if (!panel) return;
      if (panel.style.display === 'block') {
        panel.style.display = 'none';
      } else {
        panel.style.display = 'block';
        loadAlertConfig(stopid);
      }
    }

    function getWeekdayNames(wd) {
      const names = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
      let parts = [];
      for (let i = 0; i < 7; i++) {
        if (wd & (1 << i)) parts.push(names[i]);
      }
      return parts.length > 0 ? parts.join(',') : 'None';
    }

    function pad2(n) { return (n < 10 ? '0' : '') + n; }

    // ── Reset WiFi ───────────────────────────────────────────────

    async function resetWiFi() {
      if (!confirm('Reset WiFi credentials? The device will reboot into setup mode.')) return;
      try {
        await fetch('/api/reset-wifi', { method: 'POST' });
        setStatus('Rebooting into WiFi setup mode...', false);
      } catch(e) {
        setStatus('Connection error', true);
      }
    }

    // ── Event binding ───────────────────────────────────────────

    document.getElementById('lineSelect').addEventListener('change', onLineSelected);
    document.getElementById('searchBtn').addEventListener('click', searchLine);
    document.getElementById('lineInput').addEventListener('keypress', function(e) {
      if(e.key === 'Enter') searchLine();
    });
    document.getElementById('lineInput').addEventListener('input', function() {
      document.getElementById('searchBtn').disabled = !this.value.trim();
    });
    document.getElementById('stationResults').addEventListener('click', addStop);
    document.getElementById('stationResults').addEventListener('touchend', addStop);
    document.getElementById('deleteAllBtn').addEventListener('click', deleteAllStops);
    document.getElementById('resetWifiBtn').addEventListener('click', resetWiFi);

    // ── Start ───────────────────────────────────────────────────

    loadStops();
    loadLines();
  </script>
</body>
</html>
)rawliteral";
}
// --- EMBEDDED_HTML_END ---

// ── Serve root page ─────────────────────────────────────────────

void handleRoot(WebServer &server) {
    server.send(200, "text/html", getIndexHTML());
}

// ── API: GET /api/rbl-lines → proxy to till.mabe.at/rbl/ (line list) ──

void handleApiRblLines(WebServer &server) {
    String html = fetchPage("https://till.mabe.at/rbl/");
    if(html.length() == 0) {
        server.send(502, "application/json", "{\"error\":\"Upstream fetch failed\"}");
        return;
    }

    // Find <select id="line"> or first <select>
    int selPos = html.indexOf("<select id=\"line\"");
    if(selPos < 0) selPos = html.indexOf("<select id='line'");
    if(selPos < 0) selPos = html.indexOf("<select");

    if(selPos < 0) {
        server.send(200, "application/json", "[]");
        return;
    }
    int closeSel = html.indexOf("</select>", selPos);
    if(closeSel < 0) { server.send(200, "application/json", "[]"); return; }

    String block = html.substring(selPos, closeSel);
    String json;
    json.reserve(block.length());  // pre-allocate (upper bound)
    json += '[';
    bool first = true;
    int pos = 0;

    while(true) {
        int optStart = block.indexOf("<option", pos);
        if(optStart < 0) break;
        int optEnd = block.indexOf("</option>", optStart);
        if(optEnd < 0) break;

        String tag = block.substring(optStart, optEnd);

        // value="..."
        int vS = tag.indexOf("value=\"");
        if(vS < 0) { pos = optEnd + 9; continue; }
        vS += 7;
        int vE = tag.indexOf('"', vS);
        if(vE < 0) { pos = optEnd + 9; continue; }
        String val = tag.substring(vS, vE);
        if(val.length() == 0) { pos = optEnd + 9; continue; }

        // inner text
        int tS = tag.indexOf('>', vE);
        if(tS < 0) { pos = optEnd + 9; continue; }
        tS++;
        String name = tag.substring(tS);
        name.trim();

        // JSON-escape: backslash and double-quote in name
        name.replace("\\", "\\\\");
        name.replace("\"", "\\\"");

        if(!first) json += ',';
        first = false;
        json += "{\"id\":\"";
        json += val;
        json += "\",\"name\":\"";
        json += name;
        json += "\"}";

        pos = optEnd + 9;
    }
    json += ']';
    server.send(200, "application/json", json);
}

// ── API: GET /api/rbl-stations?line=XXX → proxy to till.mabe.at ──

void handleApiRblStations(WebServer &server) {
    if(!server.hasArg("line")) {
        server.send(400, "application/json", "{\"error\":\"Missing 'line'\"}");
        return;
    }
    String url = "https://till.mabe.at/rbl/?line=";
    url += server.arg("line");

    String html = fetchPage(url.c_str());
    if(html.length() == 0) {
        server.send(502, "application/json", "{\"error\":\"Upstream fetch failed\"}");
        return;
    }

    // Find <select id="station">
    int selPos = html.indexOf("<select id=\"station\"");
    if(selPos < 0) selPos = html.indexOf("<select id='station'");
    if(selPos < 0) { server.send(200, "application/json", "[]"); return; }

    int closeSel = html.indexOf("</select>", selPos);
    if(closeSel < 0) { server.send(200, "application/json", "[]"); return; }

    String block = html.substring(selPos, closeSel);
    String json;
    json.reserve(block.length());
    json += '[';
    bool first = true;
    int pos = 0;

    while(true) {
        int optStart = block.indexOf("<option", pos);
        if(optStart < 0) break;
        int optEnd = block.indexOf("</option>", optStart);
        if(optEnd < 0) break;

        String tag = block.substring(optStart, optEnd);

        // value="..."
        int vS = tag.indexOf("value=\"");
        if(vS < 0) { pos = optEnd + 9; continue; }
        vS += 7;
        int vE = tag.indexOf('"', vS);
        if(vE < 0) { pos = optEnd + 9; continue; }
        String val = tag.substring(vS, vE);
        if(val.length() == 0) { pos = optEnd + 9; continue; }

        // data-dir="..."
        String dir;
        int dS = tag.indexOf("data-dir=\"");
        if(dS >= 0) {
            dS += 10;
            int dE = tag.indexOf('"', dS);
            if(dE >= 0) dir = tag.substring(dS, dE);
        }

        // inner text
        int tS = tag.indexOf('>', vE);
        if(tS < 0) { pos = optEnd + 9; continue; }
        tS++;
        String name = tag.substring(tS);
        name.trim();

        // JSON-escape
        name.replace("\\", "\\\\");
        name.replace("\"", "\\\"");
        dir.replace("\\", "\\\\");
        dir.replace("\"", "\\\"");

        if(!first) json += ',';
        first = false;
        json += "{\"id\":\"";
        json += val;
        json += "\",\"name\":\"";
        json += name;
        json += "\",\"direction\":\"";
        json += dir;
        json += "\"}";

        pos = optEnd + 9;
    }
    json += ']';
    server.send(200, "application/json", json);
}

// ── API: POST /api/add-stop → resolve RBL/StopId + add to list ──
// Form fields: line, station, name, dir, linename

void handleApiAddStop(WebServer &server, WienerLinienStation &station) {
    if(!server.hasArg("line") || !server.hasArg("station")) {
        server.send(400, "application/json", "{\"error\":\"Missing 'line' or 'station'\"}");
        return;
    }

    String lineParam    = server.arg("line");
    String stationParam = server.arg("station");
    String stationName  = server.arg("name");
    String lineName     = server.arg("linename");

    // Build upstream URL and fetch
    String url = "https://till.mabe.at/rbl/?line=";
    url += lineParam;
    url += "&station=";
    url += stationParam;

    String page = fetchPage(url.c_str());
    if(page.length() == 0) {
        server.send(502, "application/json", "{\"error\":\"Upstream fetch failed\"}");
        return;
    }

    // Parse RBL/StopId: <big>NNNN</big>
    int stopid = 0;
    int rblPos = page.indexOf("RBL/StopId: <big>");
    if(rblPos >= 0) {
        rblPos += 17;  // skip "RBL/StopId: <big>"
        while(rblPos < (int)page.length() && page[rblPos] >= '0' && page[rblPos] <= '9') {
            stopid = stopid * 10 + (page[rblPos] - '0');
            rblPos++;
        }
    }

    if(stopid == 0) {
        server.send(404, "application/json",
            "{\"error\":\"RBL/StopId not found — try a different station\"}");
        return;
    }

    // Build LineStop
    WienerLinienStation::LineStop ls;
    ls.stopid = stopid;
    ls.linecode = fastParseInt(lineParam.c_str(), lineParam.length());

    for(auto& saved_ls : station.linestopList) {
        if(ls.stopid == saved_ls.stopid && ls.linecode == saved_ls.linecode){
            String resp = "{\"status\":\"ok\",\"stopid\":";
            resp += stopid;
            resp += ",\"duplicate\":true}";
            server.send(200, "application/json", resp);
            return;
        }
    }


    // Copy up to 3 chars of line name into ls.name
    size_t n = (lineName.length() < 3) ? lineName.length() : 3;
    for(size_t i = 0; i < 3; i++)
        ls.name[i] = (i < n) ? lineName[i] : '\0';

    // Store human-readable station name (in-memory + EEPROM)
    if(stationName.length() > 0) {
        station.stopName[stopid] = stationName;
        EEPROMWIENERLINIEN::saveStationName(stopid, stationName);
    }

    EEPROMWIENERLINIEN::add(ls.save());
    station.linestopList.push_back(ls);

    String resp = "{\"status\":\"ok\",\"stopid\":";
    resp += stopid;
    resp += '}';
    server.send(200, "application/json", resp);
}

// ── API: POST /api/delete-stop → remove from list ────────────────
// Form field: id

void handleApiDeleteStop(WebServer &server, WienerLinienStation &station) {
    if(!server.hasArg("id")) {
        server.send(400, "application/json", "{\"error\":\"Missing 'id'\"}");
        return;
    }
    int id = fastParseInt(server.arg("id").c_str(), server.arg("id").length());

    auto& vec = station.linestopList;
    for(auto it = vec.begin(); it != vec.end(); ++it) {
        if(it->stopid == id) {
            // Persist removal: need save data before erasing iterator
            auto saveData = it->save();
            EEPROMWIENERLINIEN::remove(saveData);
            EEPROMWIENERLINIEN::removeStationName(id);
            vec.erase(it);
            server.send(200, "application/json", "{\"status\":\"ok\"}");
            return;
        }
    }
    server.send(404, "application/json", "{\"error\":\"Stop not found\"}");
}

void handleApiDeleteAllStop(WebServer &server, WienerLinienStation &station) {
  EEPROMWIENERLINIEN::clear();
  EEPROMWIENERLINIEN::clearStationNames();
  station.linestopList.clear();
  station.stopName.clear();
  // Clear departures cache to match empty stop list
  station.clearDepartures();
  server.send(200, "application/json", "{\"status\":\"ok\"}");
}

// ── API: GET /api/stopids → current stop list as JSON ────────────

void handleApiGetStopids(WebServer &server, WienerLinienStation &station) {
    String json;
    json.reserve(64 + station.linestopList.size() * 64);
    json += "{\"stops\":[";
    bool first = true;

    for(auto& ls : station.linestopList) {
        if(!first) json += ',';
        first = false;
        json += "{\"id\":";
        json += ls.stopid;
        json += ",\"line\":\"";
        json += ls.linecode;
        json += "\",\"lineName\":\"";
        json += lineStopName(ls);
        json += "\"";

        auto it = station.stopName.find(ls.stopid);
        if(it != station.stopName.end() && it->second.length() > 0) {
            json += ",\"name\":\"";
            // JSON-escape the station name
            String escaped = it->second;
            escaped.replace("\\", "\\\\");
            escaped.replace("\"", "\\\"");
            json += escaped;
            json += "\"";
        }
        json += '}';
    }
    json += "]}";
    server.send(200, "application/json", json);
}

// ── Alert API ───────────────────────────────────────────────────

void handleApiGetAlerts(WebServer &server) {
    String json = EEPROMWIENERLINIEN::loadAlertsJSON();

    // Optional filter by stopid
    if (server.hasArg("stopid")) {
        int stopid = fastParseInt(server.arg("stopid").c_str(), server.arg("stopid").length());
        JsonDocument doc;
        deserializeJson(doc, json);
        JsonArray all = doc.as<JsonArray>();
        for (JsonObject entry : all) {
            if (entry["stopid"].as<int>() == stopid) {
                String filtered;
                serializeJson(entry, filtered);
                server.send(200, "application/json", filtered);
                return;
            }
        }
        server.send(200, "application/json", "{\"stopid\":" + String(stopid) + ",\"rules\":[]}");
        return;
    }

    server.send(200, "application/json", json);
}

void handleApiSaveAlerts(WebServer &server) {
    if (!server.hasArg("plain")) {
        server.send(400, "application/json", "{\"error\":\"Missing JSON body\"}");
        return;
    }

    String body = server.arg("plain");
    JsonDocument newEntry;
    DeserializationError err = deserializeJson(newEntry, body);
    if (err) {
        server.send(400, "application/json", "{\"error\":\"Invalid JSON\"}");
        return;
    }

    int stopid = newEntry["stopid"] | 0;
    if (stopid == 0) {
        server.send(400, "application/json", "{\"error\":\"Missing stopid\"}");
        return;
    }

    JsonArray newRules = newEntry["rules"].as<JsonArray>();

    // Load existing, rebuild merging in the new/updated entry
    String existing = EEPROMWIENERLINIEN::loadAlertsJSON();
    JsonDocument allDoc;
    deserializeJson(allDoc, existing);
    JsonArray oldAll = allDoc.as<JsonArray>();

    JsonDocument outDoc;
    JsonArray outArr = outDoc.to<JsonArray>();

    for (JsonObject entry : oldAll) {
        if (entry["stopid"].as<int>() != stopid) {
            outArr.add(entry);
        }
    }

    // Add/replace entry if it has rules
    if (newRules && newRules.size() > 0) {
        JsonObject obj = outArr.add<JsonObject>();
        obj["stopid"] = stopid;
        JsonArray copiedRules = obj["rules"].to<JsonArray>();
        for (JsonObject rule : newRules) {
            copiedRules.add(rule);
        }
    }

    String out;
    serializeJson(outDoc, out);
    EEPROMWIENERLINIEN::saveAlertsJSON(out);
    server.send(200, "application/json", "{\"status\":\"ok\"}");
}

// ── Legacy helpers (kept for potential external callers) ─────────

bool stopid_validator(String &numbers) {
    for(char c : numbers)
        if(!((c >= '0' && c <= '9') || c == ',' || c == ' ')) return false;
    return numbers.length() > 0;
}

std::vector<int> parse_num_vec(String &numbers) {
    std::vector<int> out;
    int cur = 0;
    bool has = false;
    for(char c : numbers) {
        if(c == ' ') continue;
        if(c == ',') { if(has) { out.push_back(cur); cur = 0; has = false; } }
        else { cur = cur * 10 + (c - '0'); has = true; }
    }
    if(has) out.push_back(cur);
    return out;
}
